#!/usr/bin/env python3
"""Generate assets/js/i18n-data.js from assets/i18n/*.json so i18n works on file:// (no fetch/CORS)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'assets' / 'i18n'
OUT = ROOT / 'assets' / 'js' / 'i18n-data.js'

data = {}
for f in sorted(SRC.glob('*.json')):
    lang = f.stem
    data[lang] = json.loads(f.read_text(encoding='utf-8'))

OUT.write_text(
    '/* AUTO-GENERATED by scripts/build_i18n.py — do not edit. Source: assets/i18n/*.json */\n'
    'window.I18N_DATA = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n',
    encoding='utf-8',
)
print(f'i18n-data.js: {len(data)} langs, {OUT.stat().st_size} bytes')
